### ISSUE TITLE
stuck at waiting for data

### ISSUE THREAD

**Issue by sail2themoon** [ohnowhathaveidone/ESP32_PDM_MIC#1]
Hi,
WiFi works, I've tried a lower sample- and clockrate, but I don't get any data:

`I (2964) micStreamer: Socket created
I (2964) micStreamer: Socket bound, port 3333
I (2974) micStreamer: Waiting for data
I (3964) main_task: Returned from app_main()
`
I've checked the ws-pin, and data-pin, seems to be OK.

Any idea what could be wrong?

edit: No change if receive.py is run before esp starts or afterwards: No more output after "receiving data" (nothing after ctrl-C, too)  Of course I've set the right ip into receive.py.

**Comment by ohnowhathaveidone** [comment]
do you provide a third commandline argument to receive.py to set doInit to True? on the first time, communication with the server needs to be initialized. 
you can probably also just set it to true in the script directly.

**Comment by sail2themoon** [comment]
I didn't had any commandline argument. But thank you, "doInit = True;" worked.
Before that there was just a 44 byte file (the header). Now the incoming stream is saved, and the output-file larger (depends on how long it's running), but it's full of zeroes, except for the wav-header.
I've tried different pins, lower samplerate.. Always zeroes. Even though I can measure the clock signals and the output signal of the mic. So there is something.. Somewhere it's not picked up.

**Comment by ohnowhathaveidone** [comment]
receive.py expects three commandline args: sample rate, name for output file and if it's supposed to set doInit. if you don't provide it with anything, it'll default to 'output' as filename and 192 kHz sample rate. doInit causes the script to trigger the ESP32's server to send data. not setting is for the situation when you already recorded once and want to continue. 
it's weird that you get no data from the mic. is it the same mic? it's a bit hard to troubleshoot this without seeing the setup. for me, opening the generated wavs in a sound editor worked...

also, be warned - the data stream seems to overwhelm the esp32 after about 5 minutes. after that, it'll start dropping packets. i haven't yet figured out what exactly is going south.

**Comment by sail2themoon** [comment]
I didn't knew that. I'm really not good in python. I've now tried with the three arguments (and without the fixed doInit), same as before: I see "got 100 ... 200 ... packets" but the file is full of zeroes.
I have a "SPH0641LU4H-1" mic. It has even the identical pinout as yours (mind that in my mic's datasheet it's actually seen from the bottom, not through the top-layer).
What did you do with the select-pin? I tried tie it to ground and to Vdd, no change.
Ok, maybe I can find a solution for the 5 min. overwhelm sometime..

edit: I've uncommented the delay in line 219 of mic_main.c: without it, the esp32 seems to crash the whole time "backtrace.. watchdog got triggered"

**Comment by ohnowhathaveidone** [comment]
that's strange... the tow mics seem to be really almost identical (at first glance). even the timing seems to be the same. 
do you have the 0.1 µF caps installed according to the reference design in the data sheet?

for select, i'm not entirely sure. i think i broke that pin out on my pcb. i'd have to check at work what it's tied to. 

do you have a scope to verify that the signals on CLK and DATA are correct and on the correct pins?

you also said that you lowered the sampling rate. can you try to set it back to its original value? i remember that figuring out the parameters for the I2S interface was a bit annoying. it wasn't documented that well and it wasn't entirely clear to me, what each setting did in detail. 

as another alternative, you may look into GrahamM's original repo that is linked in my readme: https://github.com/GrahamM/ESP32_I2S_Microphone maybe you'll have better luck with his settings.

**Comment by sail2themoon** [comment]
No I don't have that cap. But I had that mic running fine on a Pi Pico once.

Yes, I can identify the signals as CLK and DATA. If the mic gets the clock, there's data output to the esp32. I don't have a high resolution with my scope but the shapes of the signals make sense.

Yes, I've also tried the default high sample rate again. As far as I've seen, there should be at least noise in the recording if the mic can't do a specific rate.

I tried GrahamM's settings, no luck.

But I've tried: esp-idf/examples/peripherals/i2s/i2s_basic/i2s_pdm_rx.c
The rx-code must be enabled in menuconfig first. Then I've changed CLK and DATA pins to pins I also used in your project, and got input from the mic, printed as amplitude values.
This code uses a newer i2s/pdm lib "driver/i2s_pdm.h", which doesn't seem very popular, yet.

Right now I don't know what else I could try. But thank you very much for help and fast response.

Edit: just found this: https://github.com/espressif/esp-idf/tree/master/examples/peripherals/i2s/i2s_recorder  that could help

**Comment by ohnowhathaveidone** [comment]
yeah, i remember messing around with the I2S config for quite some time. it's not the most clear/intuitive interface IMO. but that's probably also related to the fact that PDM over I2S is not particularly well standardized. 

sorry that i can't help much more...

good luck!

**Comment by sail2themoon** [comment]
I successfully made recordings with my mic and https://github.com/espressif/esp-idf/tree/master/examples/peripherals/i2s/i2s_recorder
I'll try to add udp-streaming.

**Comment by ohnowhathaveidone** [comment]
alright! sounds great!
i quickly looked at espressif's code - they are using slightly different libraries than me. it may as well be that my code is outdated, it hasn't been updated in quite a while after all.
i'll close the issue with that. 

cheers!
